### ISSUE TITLE
RStoolbox was archived on CRAN, rasterPCA is no longer usable

### ISSUE THREAD

**Issue by tristanubaldi** [danddr/USE_paper#1]
Hello,

I'm trying to run your _Fagus example_ (by the way, a nice example, thanks for sharing it on GitHub) to compare it with a model I'm working on. 

However, to run your PCA, you are using the `rasterPCA` function from the `RStoolbox` package but [this package is no longer available on CRAN](https://github.com/bleutner/RStoolbox/issues/95).

Maybe you have another function to use to get the same results?

Thank you.

**Comment by danddr** [comment]
Dear Tristan, 
thanks for your message.

I have just uploaded a new function, 'rastPCA', which perform the PCA on SpatRaster objects from the terra package. I have updated the package and removed the dependency from RStoolbox: it works from my side, does it work for you as well? 

Thank you 

Daniele

**Comment by tristanubaldi** [comment]
That works perfectly for me, thank you for your help!

**Comment by ailich** [comment]
`princomp` is also now implemented in `terra` directly (rspatial/terra#1361)
